function out = dialog_fig(message,title,buttons);
global dialog_choise
dialog_choise = '';

f= figure( ...
      'Name',title,...
      'MenuBar','None',...
      'ToolBar','None',...
      'position', [500,400,500,100]);

% pnl = uipanel('Parent',f, ...
% 'Tag','dialog_panel',...
% 'BorderType', 'line', ...
% 'BorderWidth', 2, ...
% 'FontSize', 10, ...
% 'Title','Calibrating', ...
% 'units', 'pixels', ...
% 'position',[x_pos,y_pos,frame_w,frame_h]);


uicontrol(f,
      'Style','text',...
     'Units','Normalized',...
     'Position',[0 .6 1 .4],...
     'String',message);

N = length(buttons);
for i=1:N
spc = .025;
p = uicontrol(f,
      'Style','PushButton',...
     'Units','Normalized',...
     'Position',[(1/N)*(i-1) + spc, .1,  1/N - 2* spc,  .4],...
     'String',buttons{i},...
     'CallBack','global dialog_choise; dialog_choise = get(gcbo,''String'');close(gcbf)');
end
figure(f)

return
